Repository ColtAllen/btyd, pull requests merged in 2022-07, with the labels that each got.

#31 Cleanup Alpha Release
  btyd/models/__init__.py
  btyd/models/beta_geo_model.py
  btyd/utils.py
  pyproject.toml
  requirements.txt
  tests/__main__.py
  tests/conftest.py
  tests/test_models.py
  tests/test_utils.py
Labels: enhancement

#32 Persist Full InferenceData Object as JSON
  btyd/models/__init__.py
  btyd/models/beta_geo_model.py
  tests/test_models.py
Labels: enhancement

#33 Fully Bayesian API Enhancements
  btyd/__init__.py
  btyd/models/__init__.py
  btyd/models/beta_geo_model.py
  tests/test_base_model.py
  tests/test_beta_geo_model.py
Labels: bug, enhancement, good first issue

#36 Removed Model Persistence
  btyd/models/__init__.py
  tests/test_beta_geo_model.py
Labels: enhancement

#37 Update and Test Documentation
  docs/Changelog.rst
  docs/Makefile
  docs/Saving and loading model.md
  docs/conf.py
  docs/docs_requirements.txt
  docs/intro.rst
  docs/make.bat
  docs/modules.rst
  docs/source/Changelog.rst
  docs/source/Generate RFM Summaries From a SQL Store.md
  docs/source/High Level Overview.md
  docs/source/Saving and Loading Models.md
  docs/source/User Guide.md
  docs/source/_static/alivematrix.png
  docs/source/_static/betageo_graph.png
  docs/source/_static/btyd_plotting.png
  docs/source/_static/btyd_workflow.png
  docs/source/_static/holdout_graph.png
  docs/source/_static/models_uml.png
  docs/source/_static/palive_history.png
  docs/source/_static/plotperiodtrans.png
  docs/source/_static/rfmatrix.png
  docs/source/btyd.datasets.rst
  docs/source/btyd.fitters.rst
  docs/source/btyd.models.rst
  docs/source/btyd.rst
  docs/source/call_graph_modules.html
  docs/source/conf.py
  docs/source/index.rst
  docs/source/intro.rst
  docs/source/lifetimes-all-tests-graph.html
  pyproject.toml
Labels: documentation

#38 CI/CD Proposal
  .github/workflows/ci.yml
  Makefile
  pyproject.toml
  setup.cfg
Labels: enhancement

#39 Added readthedocs.yaml
  docs/source/High Level Overview.md
  docs/source/User Guide.md
  readthedocs.yaml
Labels: documentation

#41 Model Persistence Re-Added
  .gitignore
  btyd/models/__init__.py
  docs/build_requirements.txt
  docs/source/Saving and Loading Models.md
  pyproject.toml
  readthedocs.yaml
  tests/test_beta_geo_model.py
Labels: enhancement

#44 Beta Release
  CHANGELOG.md
  README.md
  btyd/__init__.py
  btyd/models/__init__.py
  btyd/models/beta_geo_model.py
  docs/btyd_models_uml.png
  docs/source/Changelog.rst
Labels: bug, documentation, enhancement
